name: "EK Perfecto"
description: "Action for checking RPM files with Perfecto"
author: "ESSENTIALKAOS"

branding:
  icon: 'package'
  color: 'white'

inputs:
  files:
    description: "List of RPM files to check"
    required: true

  image:
    description: "Name of Perfecto docker image"
    required: false
    default: "ghcr.io/essentialkaos/perfecto:micro"

  format:
    description: "Output format (github|summary|tiny|short)"
    default: "github"
    required: false

  absolve:
    description: "Disable some checks by their ID"
    required: false

  error-level:
    description: "Return non-zero exit code if alert level greater than given (notice|warning|error|critical)"
    required: false

runs:
  using: "composite"
  steps:
    - id: perfecto-install
      name: Download Perfecto docker image
      shell: bash
      run: |
        # [perfecto-install]

        echo -e "::group::\033[34mDownloading Perfecto Docker image…\033[0m"
        docker pull "${{inputs.image}}"
        echo "::endgroup::"

        echo -e "::group::\033[34mDownloading Perfecto helper script…\033[0m"
        wget -O $GITHUB_ACTION_PATH/perfecto-container https://kaos.sh/perfecto/perfecto-container
        chmod +x $GITHUB_ACTION_PATH/perfecto-container
        echo "::endgroup::"

    - id: perfecto-set-options
      name: Set Perfecto options
      shell: bash
      run : |
        # [perfecto-set-options]

        declare -a options

        if [[ -n "${{inputs.format}}" ]] ; then
          options+=("-f ${{inputs.format}}")
        fi

        if [[ -n "${{inputs.absolve}}" ]] ; then
          options+=("-A ${{inputs.absolve}}")
        fi

        if [[ -n "${{inputs.error-level}}" ]] ; then
          options+=("-e ${{inputs.error-level}}")
        fi

        echo -e "::group::\033[34mPerfecto configuration…\033[0m"
        if [[ ${#options[@]} -eq 0 ]] ; then
          echo "Options: -no-set-"
        else
          echo "Options: ${options[@]}"
        fi
        echo "::endgroup::"

        echo "options=${options[@]}" >> $GITHUB_OUTPUT

    - id: perfecto-version-print
      name: Print Perfecto version info
      shell: bash
      run: |
        # [perfecto-version-print]

        echo -e "::group::\033[34mPrint Perfecto version…\033[0m"
        docker run --rm "${{inputs.image}}" --version
        echo "::endgroup::"

    - id: perfecto-check
      name: Check RPM files with Perfecto
      shell: bash
      run: |
        # [perfecto-check]

        echo -e "\033[34mRunning Perfecto…\033[0m"

        export IMAGE="${{inputs.image}}"

        for spec_file in ${{inputs.files}} ; do
          echo -e "\nChecking $spec_file…"

          $GITHUB_ACTION_PATH/perfecto-container ${{steps.perfecto-set-options.outputs.options}} "$spec_file"

          if [[ $? -ne 0 ]] ; then
            check_failed=true
          fi
        done

        if [[ -n "$check_failed" ]] ; then
          exit 1
        fi
